

url-api: https://indodax.com/api

market:
  - btc_idr
  - ten_btc
  - ten_idr
  # - btc_ten , and etc

delay-each-market: 0  #in seconds


limit : 10  # database load limit each time
min-actionable-amount : 1_000_000 # min amount at the price point